// <auto-generated />
using DB.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace DB.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20220109221206_first")]
    partial class first
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("DB.Models.Monster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("ArmorClass")
                        .HasColumnType("integer");

                    b.Property<int>("AttackModifier")
                        .HasColumnType("integer");

                    b.Property<int>("AttackPerRound")
                        .HasColumnType("integer");

                    b.Property<int>("Damage")
                        .HasColumnType("integer");

                    b.Property<int>("DamageModifier")
                        .HasColumnType("integer");

                    b.Property<int>("HitPoints")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Weapon")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Monsters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArmorClass = 15,
                            AttackModifier = 5,
                            AttackPerRound = 2,
                            Damage = 6,
                            DamageModifier = 8,
                            HitPoints = 10,
                            Name = "Wretched",
                            Weapon = 15
                        },
                        new
                        {
                            Id = 2,
                            ArmorClass = 9,
                            AttackModifier = 44,
                            AttackPerRound = 11,
                            Damage = 13,
                            DamageModifier = 8,
                            HitPoints = 93,
                            Name = "Flesh Golem",
                            Weapon = 4
                        },
                        new
                        {
                            Id = 3,
                            ArmorClass = 10,
                            AttackModifier = 4,
                            AttackPerRound = 2,
                            Damage = 7,
                            DamageModifier = 6,
                            HitPoints = 15,
                            Name = "Cow",
                            Weapon = 2
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
